spring:
  datasource:
    url: jdbc:mysql://localhost/elearning?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 6000
      max-lifetime: 300000
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 0
  jpa:
    hibernate:
      #更新或创建数据库表结构
      ddl-auto: update
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #输出执行sql
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect